name: continuous-integration-foo

on:
  pull_request:
    branches:
      = master

  jobs:
    build-and-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1 #checksout master
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1 #setup java; use actions with following commands
          with:
            java-version: 1.8

        - name: Build with Gradle!
          working-directory: .
          run: ./gradlew build -x test # -x means exclude

        - name: Run tests
          working-directory: .
          run: ./gradlew test