name: continuous-integration-foo

on:
    push:
        branches:
            - master

jobs:
    build-and-test:
        runs-on:  ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Build with Gradle!
              working-directory: .
              run: ./gradlew build -x test

            - name: Run tests
              working-directory: .
              run: ./gradlew test

    system-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1

        - name: Run Docker Compose
          working-directory: .
          run: docker-compose up -d --build

        - uses: actions/setup-python@v1
          with:
              python-version: '3.7'
        - run: pip install -U pytest requests


#        - name: Install pytest and requests
#          working-directory: .
#          run: pip3 install -U pytest && pip3 install -U requests

        - name: Run system tests
          working-directory: .
          run: pytest

        - name: Purge containers
          working-directory: .
          run: docker-compose down

